site_name: Shrub
theme: readthedocs
site_author: "cha0s"
repo_url: https://github.com/cha0s/shrub
include_search: true
docs_dir: 'docs'
site_dir: 'gh-pages'
pages:
- [index.md, 'Home']
- [hooks.md, 'Hooks']
- [todos.md, 'TODO list']
- [source/client/app.litcoffee, 'Source code', 'client/app.litcoffee']
- [source/client/packages.litcoffee, 'Source code', 'client/packages.litcoffee']
- [source/client/require.litcoffee, 'Source code', 'client/require.litcoffee']
- [source/dox.litcoffee, 'Source code', 'dox.litcoffee']
- [source/packages/shrub-form/index.litcoffee, 'Source code', 'packages/shrub-form/index.litcoffee']
- [source/server.litcoffee, 'Source code', 'server.litcoffee']
